export interface SurahInJuz {
  nama: string;
  ayatMulai: number;
  ayatSelesai: number;
  totalAyat: number;
}

export const pemetaanJuz: Record<number, SurahInJuz[]> = {
  1: [
    { nama: "Al-Fatihah", ayatMulai: 1, ayatSelesai: 7, totalAyat: 7 },
    { nama: "Al-Baqarah", ayatMulai: 1, ayatSelesai: 141, totalAyat: 286 },
  ],
  2: [
    { nama: "Al-Baqarah", ayatMulai: 142, ayatSelesai: 252, totalAyat: 286 },
  ],
  3: [
    { nama: "Al-Baqarah", ayatMulai: 253, ayatSelesai: 286, totalAyat: 286 },
    { nama: "Ali 'Imran", ayatMulai: 1, ayatSelesai: 92, totalAyat: 200 },
  ],
  4: [
    { nama: "Ali 'Imran", ayatMulai: 93, ayatSelesai: 200, totalAyat: 200 },
    { nama: "An-Nisa'", ayatMulai: 1, ayatSelesai: 23, totalAyat: 176 },
  ],
  5: [
    { nama: "An-Nisa'", ayatMulai: 24, ayatSelesai: 147, totalAyat: 176 },
  ],
  6: [
    { nama: "An-Nisa'", ayatMulai: 148, ayatSelesai: 176, totalAyat: 176 },
    { nama: "Al-Ma'idah", ayatMulai: 1, ayatSelesai: 81, totalAyat: 120 },
  ],
  7: [
    { nama: "Al-Ma'idah", ayatMulai: 82, ayatSelesai: 120, totalAyat: 120 },
    { nama: "Al-An'am", ayatMulai: 1, ayatSelesai: 110, totalAyat: 165 },
  ],
  8: [
    { nama: "Al-An'am", ayatMulai: 111, ayatSelesai: 165, totalAyat: 165 },
    { nama: "Al-A'raf", ayatMulai: 1, ayatSelesai: 87, totalAyat: 206 },
  ],
  9: [
    { nama: "Al-A'raf", ayatMulai: 88, ayatSelesai: 206, totalAyat: 206 },
    { nama: "Al-Anfal", ayatMulai: 1, ayatSelesai: 40, totalAyat: 75 },
  ],
  10: [
    { nama: "Al-Anfal", ayatMulai: 41, ayatSelesai: 75, totalAyat: 75 },
    { nama: "At-Taubah", ayatMulai: 1, ayatSelesai: 92, totalAyat: 129 },
  ],
  11: [
    { nama: "At-Taubah", ayatMulai: 93, ayatSelesai: 129, totalAyat: 129 },
    { nama: "Yunus", ayatMulai: 1, ayatSelesai: 109, totalAyat: 109 },
    { nama: "Hud", ayatMulai: 1, ayatSelesai: 5, totalAyat: 123 },
  ],
  12: [
    { nama: "Hud", ayatMulai: 6, ayatSelesai: 123, totalAyat: 123 },
    { nama: "Yusuf", ayatMulai: 1, ayatSelesai: 52, totalAyat: 111 },
  ],
  13: [
    { nama: "Yusuf", ayatMulai: 53, ayatSelesai: 111, totalAyat: 111 },
    { nama: "Ar-Ra'd", ayatMulai: 1, ayatSelesai: 43, totalAyat: 43 },
    { nama: "Ibrahim", ayatMulai: 1, ayatSelesai: 52, totalAyat: 52 },
  ],
  14: [
    { nama: "Al-Hijr", ayatMulai: 1, ayatSelesai: 99, totalAyat: 99 },
    { nama: "An-Nahl", ayatMulai: 1, ayatSelesai: 128, totalAyat: 128 },
  ],
  15: [
    { nama: "Al-Isra'", ayatMulai: 1, ayatSelesai: 111, totalAyat: 111 },
    { nama: "Al-Kahfi", ayatMulai: 1, ayatSelesai: 74, totalAyat: 110 },
  ],
  16: [
    { nama: "Al-Kahfi", ayatMulai: 75, ayatSelesai: 110, totalAyat: 110 },
    { nama: "Maryam", ayatMulai: 1, ayatSelesai: 98, totalAyat: 98 },
    { nama: "Ta-Ha", ayatMulai: 1, ayatSelesai: 135, totalAyat: 135 },
  ],
  17: [
    { nama: "Al-Anbiya'", ayatMulai: 1, ayatSelesai: 112, totalAyat: 112 },
    { nama: "Al-Hajj", ayatMulai: 1, ayatSelesai: 78, totalAyat: 78 },
  ],
  18: [
    { nama: "Al-Mu'minun", ayatMulai: 1, ayatSelesai: 118, totalAyat: 118 },
    { nama: "An-Nur", ayatMulai: 1, ayatSelesai: 64, totalAyat: 64 },
    { nama: "Al-Furqan", ayatMulai: 1, ayatSelesai: 20, totalAyat: 77 },
  ],
  19: [
    { nama: "Al-Furqan", ayatMulai: 21, ayatSelesai: 77, totalAyat: 77 },
    { nama: "Asy-Syu'ara'", ayatMulai: 1, ayatSelesai: 227, totalAyat: 227 },
    { nama: "An-Naml", ayatMulai: 1, ayatSelesai: 55, totalAyat: 93 },
  ],
  20: [
    { nama: "An-Naml", ayatMulai: 56, ayatSelesai: 93, totalAyat: 93 },
    { nama: "Al-Qasas", ayatMulai: 1, ayatSelesai: 88, totalAyat: 88 },
    { nama: "Al-'Ankabut", ayatMulai: 1, ayatSelesai: 45, totalAyat: 69 },
  ],
  21: [
    { nama: "Al-'Ankabut", ayatMulai: 46, ayatSelesai: 69, totalAyat: 69 },
    { nama: "Ar-Rum", ayatMulai: 1, ayatSelesai: 60, totalAyat: 60 },
    { nama: "Luqman", ayatMulai: 1, ayatSelesai: 34, totalAyat: 34 },
    { nama: "As-Sajdah", ayatMulai: 1, ayatSelesai: 30, totalAyat: 30 },
    { nama: "Al-Ahzab", ayatMulai: 1, ayatSelesai: 30, totalAyat: 73 },
  ],
  22: [
    { nama: "Al-Ahzab", ayatMulai: 31, ayatSelesai: 73, totalAyat: 73 },
    { nama: "Saba'", ayatMulai: 1, ayatSelesai: 54, totalAyat: 54 },
    { nama: "Fatir", ayatMulai: 1, ayatSelesai: 45, totalAyat: 45 },
    { nama: "Ya-Sin", ayatMulai: 1, ayatSelesai: 27, totalAyat: 83 },
  ],
  23: [
    { nama: "Ya-Sin", ayatMulai: 28, ayatSelesai: 83, totalAyat: 83 },
    { nama: "As-Saffat", ayatMulai: 1, ayatSelesai: 182, totalAyat: 182 },
    { nama: "Sad", ayatMulai: 1, ayatSelesai: 88, totalAyat: 88 },
    { nama: "Az-Zumar", ayatMulai: 1, ayatSelesai: 31, totalAyat: 75 },
  ],
  24: [
    { nama: "Az-Zumar", ayatMulai: 32, ayatSelesai: 75, totalAyat: 75 },
    { nama: "Ghafir", ayatMulai: 1, ayatSelesai: 85, totalAyat: 85 },
    { nama: "Fussilat", ayatMulai: 1, ayatSelesai: 46, totalAyat: 54 },
  ],
  25: [
    { nama: "Fussilat", ayatMulai: 47, ayatSelesai: 54, totalAyat: 54 },
    { nama: "Asy-Syura", ayatMulai: 1, ayatSelesai: 53, totalAyat: 53 },
    { nama: "Az-Zukhruf", ayatMulai: 1, ayatSelesai: 89, totalAyat: 89 },
    { nama: "Ad-Dukhan", ayatMulai: 1, ayatSelesai: 59, totalAyat: 59 },
    { nama: "Al-Jatsiyah", ayatMulai: 1, ayatSelesai: 37, totalAyat: 37 },
  ],
  26: [
    { nama: "Al-Ahqaf", ayatMulai: 1, ayatSelesai: 35, totalAyat: 35 },
    { nama: "Muhammad", ayatMulai: 1, ayatSelesai: 38, totalAyat: 38 },
    { nama: "Al-Fath", ayatMulai: 1, ayatSelesai: 29, totalAyat: 29 },
    { nama: "Al-Hujurat", ayatMulai: 1, ayatSelesai: 18, totalAyat: 18 },
    { nama: "Qaf", ayatMulai: 1, ayatSelesai: 45, totalAyat: 45 },
    { nama: "Adz-Dzariyat", ayatMulai: 1, ayatSelesai: 30, totalAyat: 60 },
  ],
  27: [
    { nama: "Adz-Dzariyat", ayatMulai: 31, ayatSelesai: 60, totalAyat: 60 },
    { nama: "At-Tur", ayatMulai: 1, ayatSelesai: 49, totalAyat: 49 },
    { nama: "An-Najm", ayatMulai: 1, ayatSelesai: 62, totalAyat: 62 },
    { nama: "Al-Qamar", ayatMulai: 1, ayatSelesai: 55, totalAyat: 55 },
    { nama: "Ar-Rahman", ayatMulai: 1, ayatSelesai: 78, totalAyat: 78 },
    { nama: "Al-Waqi'ah", ayatMulai: 1, ayatSelesai: 96, totalAyat: 96 },
    { nama: "Al-Hadid", ayatMulai: 1, ayatSelesai: 29, totalAyat: 29 },
  ],
  28: [
    { nama: "Al-Mujadilah", ayatMulai: 1, ayatSelesai: 22, totalAyat: 22 },
    { nama: "Al-Hasyr", ayatMulai: 1, ayatSelesai: 24, totalAyat: 24 },
    { nama: "Al-Mumtahanah", ayatMulai: 1, ayatSelesai: 13, totalAyat: 13 },
    { nama: "As-Saff", ayatMulai: 1, ayatSelesai: 14, totalAyat: 14 },
    { nama: "Al-Jumu'ah", ayatMulai: 1, ayatSelesai: 11, totalAyat: 11 },
    { nama: "Al-Munafiqun", ayatMulai: 1, ayatSelesai: 11, totalAyat: 11 },
    { nama: "At-Taghabun", ayatMulai: 1, ayatSelesai: 18, totalAyat: 18 },
    { nama: "At-Talaq", ayatMulai: 1, ayatSelesai: 12, totalAyat: 12 },
    { nama: "At-Tahrim", ayatMulai: 1, ayatSelesai: 12, totalAyat: 12 },
  ],
  29: [
    { nama: "Al-Mulk", ayatMulai: 1, ayatSelesai: 30, totalAyat: 30 },
    { nama: "Al-Qalam", ayatMulai: 1, ayatSelesai: 52, totalAyat: 52 },
    { nama: "Al-Haqqah", ayatMulai: 1, ayatSelesai: 52, totalAyat: 52 },
    { nama: "Al-Ma'arij", ayatMulai: 1, ayatSelesai: 44, totalAyat: 44 },
    { nama: "Nuh", ayatMulai: 1, ayatSelesai: 28, totalAyat: 28 },
    { nama: "Al-Jinn", ayatMulai: 1, ayatSelesai: 28, totalAyat: 28 },
    { nama: "Al-Muzzammil", ayatMulai: 1, ayatSelesai: 20, totalAyat: 20 },
    { nama: "Al-Muddatsir", ayatMulai: 1, ayatSelesai: 56, totalAyat: 56 },
    { nama: "Al-Qiyamah", ayatMulai: 1, ayatSelesai: 40, totalAyat: 40 },
    { nama: "Al-Insan", ayatMulai: 1, ayatSelesai: 31, totalAyat: 31 },
    { nama: "Al-Mursalat", ayatMulai: 1, ayatSelesai: 50, totalAyat: 50 },
  ],
  30: [
    { nama: "An-Naba'", ayatMulai: 1, ayatSelesai: 40, totalAyat: 40 },
    { nama: "An-Nazi'at", ayatMulai: 1, ayatSelesai: 46, totalAyat: 46 },
    { nama: "'Abasa", ayatMulai: 1, ayatSelesai: 42, totalAyat: 42 },
    { nama: "At-Takwir", ayatMulai: 1, ayatSelesai: 29, totalAyat: 29 },
    { nama: "Al-Infitar", ayatMulai: 1, ayatSelesai: 19, totalAyat: 19 },
    { nama: "Al-Mutaffifin", ayatMulai: 1, ayatSelesai: 36, totalAyat: 36 },
    { nama: "Al-Insyiqaq", ayatMulai: 1, ayatSelesai: 25, totalAyat: 25 },
    { nama: "Al-Buruj", ayatMulai: 1, ayatSelesai: 22, totalAyat: 22 },
    { nama: "At-Tariq", ayatMulai: 1, ayatSelesai: 17, totalAyat: 17 },
    { nama: "Al-A'la", ayatMulai: 1, ayatSelesai: 19, totalAyat: 19 },
    { nama: "Al-Ghasyiyah", ayatMulai: 1, ayatSelesai: 26, totalAyat: 26 },
    { nama: "Al-Fajr", ayatMulai: 1, ayatSelesai: 30, totalAyat: 30 },
    { nama: "Al-Balad", ayatMulai: 1, ayatSelesai: 20, totalAyat: 20 },
    { nama: "Asy-Syams", ayatMulai: 1, ayatSelesai: 15, totalAyat: 15 },
    { nama: "Al-Lail", ayatMulai: 1, ayatSelesai: 21, totalAyat: 21 },
    { nama: "Ad-Duha", ayatMulai: 1, ayatSelesai: 11, totalAyat: 11 },
    { nama: "Asy-Syarh", ayatMulai: 1, ayatSelesai: 8, totalAyat: 8 },
    { nama: "At-Tin", ayatMulai: 1, ayatSelesai: 8, totalAyat: 8 },
    { nama: "Al-'Alaq", ayatMulai: 1, ayatSelesai: 19, totalAyat: 19 },
    { nama: "Al-Qadr", ayatMulai: 1, ayatSelesai: 5, totalAyat: 5 },
    { nama: "Al-Bayyinah", ayatMulai: 1, ayatSelesai: 8, totalAyat: 8 },
    { nama: "Az-Zalzalah", ayatMulai: 1, ayatSelesai: 8, totalAyat: 8 },
    { nama: "Al-'Adiyat", ayatMulai: 1, ayatSelesai: 11, totalAyat: 11 },
    { nama: "Al-Qari'ah", ayatMulai: 1, ayatSelesai: 11, totalAyat: 11 },
    { nama: "At-Takatsur", ayatMulai: 1, ayatSelesai: 8, totalAyat: 8 },
    { nama: "Al-'Asr", ayatMulai: 1, ayatSelesai: 3, totalAyat: 3 },
    { nama: "Al-Humazah", ayatMulai: 1, ayatSelesai: 9, totalAyat: 9 },
    { nama: "Al-Fil", ayatMulai: 1, ayatSelesai: 5, totalAyat: 5 },
    { nama: "Quraisy", ayatMulai: 1, ayatSelesai: 4, totalAyat: 4 },
    { nama: "Al-Ma'un", ayatMulai: 1, ayatSelesai: 7, totalAyat: 7 },
    { nama: "Al-Kautsar", ayatMulai: 1, ayatSelesai: 3, totalAyat: 3 },
    { nama: "Al-Kafirun", ayatMulai: 1, ayatSelesai: 6, totalAyat: 6 },
    { nama: "An-Nasr", ayatMulai: 1, ayatSelesai: 3, totalAyat: 3 },
    { nama: "Al-Lahab", ayatMulai: 1, ayatSelesai: 5, totalAyat: 5 },
    { nama: "Al-Ikhlas", ayatMulai: 1, ayatSelesai: 4, totalAyat: 4 },
    { nama: "Al-Falaq", ayatMulai: 1, ayatSelesai: 5, totalAyat: 5 },
    { nama: "An-Nas", ayatMulai: 1, ayatSelesai: 6, totalAyat: 6 },
  ],
};
